### ISSUE TITLE
Azure DevOps sign VSTO ClickOnce AddIn

### ISSUE THREAD

**Issue by chrpai** [Azure/trusted-signing-action#63]
I've successfully used azure trusted signing (and action) in pipelines. Now I have a situation with a legacy .csproj VSTO clickonce addin.  The msbuild has a property to enable signing and a property called ManifestCertificateThumbprint which points to the cert.  This doesn't work becajuse we don't have the cert available to us anymore.  I tried turning off signing so I could sign it postbuild but it gave the error :

Error : Cannot build because the ClickOnce manifest signing option is not selected. To select this option, open the project property pages, click the Signing tab, and then select "Sign the ClickOnce manifests."

Does anyone know how to solve this?  Do I need to install a self sign cert to get past this and then remove the signing and resign it postbuild?  Is there another path such as migrating to a SDK style project that works with newer tooling?

**Comment by japarson** [comment]
Hi @chrpai ,

What happens if you set the following properties?
<SignManifests>false</SignManifests>
<SignAssembly>false</SignAssembly>
<ManifestCertificateThumbprint></ManifestCertificateThumbprint>
<ManifestKeyFile></ManifestKeyFile>

The idea is to disable or empty all properties related to signing. If that doesn't work, you can try to get a binlog of your build and track down where that error is getting thrown from.

**Comment by chrpai** [comment]
I've a DevOps consultant and this project is a customers so I'm trying to be as non evasive as possible.  At this point I configured the pipeline to install to download a secure file and install it was a test certificate.  Then in the MSBuild I pass a property telling it to use that thumbprint. I'm able to get the sln to build now and will take care of signing it with the trusted signing action as a postbuild step.
